### ISSUE TITLE
Error "Invalid RootFS image"

### ISSUE THREAD

**Issue by teerasak** [timoxa0/Guide-Linux-Nabu#2]
lon-deployer "C:\v2-nabu_linux\ArchLinuxArmPlasma.img"

[06:30:04] Invalid RootFS image

Thanks
( please make ubuntu-nobal.img for V1)

**Comment by timoxa0** [comment]
You can use it for v1: boot v1 recovery for partition, flash rootfs with fastboot and use postinstall script from v2 recovery, which you can find [here](https://timoxa0.su/?dir=share/nabu/deployer).

**Comment by teerasak** [comment]
After "Invalid RootFS image had fixed, but new error 

C:\platform-tools-linux>lon-deployer UbuntuDesktop_24.04.img
Username for linux: tom
Password for tom:
Size of linux partition (leave empty to skip if possible):
[02:45:14] Username: tom
           Password: qaz1wsx2
           Partition size: Not changed
           Device: 8d6b4413
Is it ok? [y/n] (n): y
[02:45:40] Device connected
           Cleaning linux and esp
           Booting OrangeFox recovery
Downloading orangefox.img ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 64.7/64.7 MB • 1.1 MB/s • 0:00:00
[02:47:24] EFI partition formated
[02:47:27] Flashing RootFS
Uploading RootFS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 77.8% • 3.0/3.8 GB • 162.4 MB/s • 0:00:06
Traceback (most recent call last):
  File "run.py", line 2, in <module>
  File "lon_deployer\main.py", line 260, in main
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[9044] Failed to execute script 'run' due to unhandled exception!

**Comment by timoxa0** [comment]
Fixed in [v1.0.3](https://github.com/timoxa0/LoN-Deployer/releases/tag/v1.0.3)
