### ISSUE TITLE
Cannot find power supply "ln8000-charger"

### ISSUE THREAD

**Issue by EralpCelebi** [timoxa0/Guide-Linux-Nabu#3]
https://gist.github.com/EralpCelebi/e9ada0cecf0ab27e1bbbea6e83207486

I suspect there is something wrong with timings. I believe @maverickjb builds the LN8000 driver as a module.  Maybe the load time is necessary.

**Comment by EralpCelebi** [comment]
Needless to say, this breaks fast charging.

**Comment by timoxa0** [comment]
Can you please provide this bc it works for me on archlinux arm with edk2-uefi:
- Boot method: UEFI | Switch2Linux
- Distro name and version

**Comment by EralpCelebi** [comment]
I am using one of your images for Arch Linux on Arm with Plasma I found from the "latest" folder. I tried using the edk2-uefi that was made for the WoA project however I couldn't get it to boot with grub properly (I am assuming this is an Arch Linux package problem more than anything)

I have also checked if the downstream reports a similar problem and it does report the same 

`ln8000_charger 1-0051: fail to detect ln8000 on i2c_bus(addr=0x51)`

however without the rest of the messages and is capable of fast charging.

**Comment by timoxa0** [comment]
I currently cannot reproduce your ln8000 problem, for me it detects PD charger and can use it.
https://gist.github.com/timoxa0/82a31f245a4d50cfeabdc1aa81257bce

**Comment by EralpCelebi** [comment]
I actually figured out what the problem was thanks to @map220v. Turns out I have one of the early builds of the tablet that used a  bq2597x IC instead of an ln8000. It has to be ported from downstream (or taken from the vayu mainline fork if it has the driver) for it to be solved.  Thank you for your help.
